[project]
name = "session05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy==2.0.2"
    "google-genai>=1.41.0",
    "mcp[cli]>=1.16.0",
    "pillow>=11.3.0",
    "pywinauto>=0.6.9",
]
