[project]
name = "cot-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.51.0",
    "mcp[cli]>=1.21.2",
    "rich>=14.2.0",
]
